### ISSUE TITLE
Development server shows a blank screen

### ISSUE THREAD

**Issue by ian-eulith** [LedgerHQ/wallet-connect-live-app#112]
I followed the steps in the README to set up a development environment (including creating `.env.local` with a WalletConnect project ID), but when I run `yarn dev` and open http://localhost:3000, I just see a blank screen. I see a `NO CONFIG FOR SENTRY` error in both the browser console and the dev server logs; unsure if that's the issue.

Is this expected?

Also, when I ran `proto use`, I got:

```
Error: toml::parse_file

  × Failed to parse TOML file ~/Code/wallet-connect-live-app/.prototools.
  ╰─▶ TOML parse error at line 1, column 1
        |
      1 | node = "18"
        | ^^^^^^^^^^^
      Invalid version or requirement 18.
```

**Comment by mcayuelas-ledger** [comment]
Hello, thanks for reaching us :) 

- for the first one `NO CONFIG FOR SENTRY` don't worry it's normal

- concerning proto did you follow the setup? https://moonrepo.dev/docs/proto/install

**Comment by mcayuelas-ledger** [comment]
To see the screen appear, you need to launch the application locally and then use the `localManifest` in LedgerLive.

If you just launch the application with yarn you will get a blank screen

Go to  Settings > Developer > Add a local app and Browse your localManifest
