### ISSUE TITLE
Wallet Connect 2 wrong signature for hex message

### ISSUE THREAD

**Issue by gvoltr** [LedgerHQ/wallet-connect-live-app#121]
Greetings! While testing WC with ledger I found some weird behavior. Most of the messages we are passing from our app to the ledger are signed fine but signature of hex strings is not correct.

For instance I'm trying to sign this string "0x1e856e530dcc8ba13b362d6a43eeb104fda6cbfbe465fdf13d004e06ce12ba8d". 
In ledger app I see this hex converted to some invalid string. 

![Screenshot_2023-09-14-16-01-52-002_com ledger live](https://github.com/LedgerHQ/wallet-connect-live-app/assets/4526572/59608fd3-835f-42f4-ae0d-3bde9609751f)

On the ledger device I see message in different format 

![IMG_0560](https://github.com/LedgerHQ/wallet-connect-live-app/assets/4526572/1db6f8c6-93ea-4fc5-83b0-c3d34110835d)

After signing this on ledger device I do get result in our app but, the signature is invalid. 
This exact flow works fine with other wallets. 
Anything I can do from our app side to fix this issue?

**Comment by gvoltr** [comment]
I believe this issue still exists, can we reopen?

**Comment by PaulUD** [comment]
@mcayuelas-ledger this issue is still present. Can we please reopen, thanks.

**Comment by mcayuelas-ledger** [comment]
@Justkant @ComradeAERGO

**Comment by gvoltr** [comment]
Hello! Thanks for the response!
We have 2 types of messages that our app signs.
- First type is a human readable message that we convert into a hex string with UTF-8 charset, this works fine with ledger.
- Second type is raw hex string (example in the first message), it is not a valid UTF-8 and should be signed as it is. This one is not working with ledger.

I just rechecked this with Metamask and Trust wallets.

For UI part wallets seems to check if hex is a valid UTF-8 then readable string is displayed, if not - raw hex message is displayed. Both wallets produce correct signature for the second type of message.
![Screenshot_2024-07-10-14-59-10-812_com wallet crypto trustapp](https://github.com/LedgerHQ/wallet-connect-live-app/assets/4526572/addaaadb-95b1-4722-af1c-eeaae14f8565)
![Screenshot_2024-07-10-14-55-32-451_io metamask](https://github.com/LedgerHQ/wallet-connect-live-app/assets/4526572/985f49c9-686b-4b11-90d9-adbb61e48995)


In our app when we sign with a private key, both types works as well. Here is the example. This code uses `org.web3j` library.
```
val data = Numeric.hexStringToByteArray(message)
val signature = Sign.signPrefixedMessage(data, keyPair)
```

**Comment by RamyEB** [comment]
Hi @gvoltr,

Thank you for your feedback.

After conducting severals tests on other wallets, we have concluded that we will not integrate a display adaptation feature based on the received message for more clarity and transparency for the end user.

We recommend using a method for encoding valid UTF-8 values in hex, as advised earlier 

```
import * as encoding from "@walletconnect/encoding";
encoding.utf8ToHex(message, true);
```

or in the [Metamask documentation](https://docs.metamask.io/wallet/reference/personal_sign/).

**Comment by TangCYxy** [comment]
@gvoltr hello buddy, how you guys resolve this problem? 

we are facing the same problems as well.

the situation is a 32 bytes hex string need to be signed, metamask and other wallet works well while ledger returns wrong signature.

**Comment by gvoltr** [comment]
@TangCYxy Hey! We dropped the idea of signing this type of message with ledger app. Asking users to connect ledger device to Metamask app and sign this way.

**Comment by TangCYxy** [comment]
> @TangCYxy Hey! We dropped the idea of signing this type of message with ledger app. Asking users to connect ledger device to Metamask app and sign this way.

thx so much! Now we will probably put this ledger signing bug aside, choose asking users to sign with eip712 or using metamask to proxy ledger signing requests like you do
