### ISSUE TITLE
Support eth_signTypedData_v4

### ISSUE THREAD

**Issue by tinaszheng** [LedgerHQ/wallet-connect-live-app#55]
Hey all! The Uniswap Interface sends `eth_signTypedData_v4` requests as part of our new Permit2 token approval flow. We've gotten a number of tickets from users who have connected with their Ledger wallets through WalletConnect that get stuck on the signature signing step. It looks like the callback through WalletConnect hangs indefinitely instead of properly erroring with a message that says the method is unsupported. The Uniswap interface can smartly detect errors because of unsupported methods and fall back to either `eth_signTypedData` or `eth_sign`.

I see that v4 signing is supported in other Ledger flows though - can you add support for it through WalletConnect as well? Either that, or properly error for unsupported methods. Thank you!

In the meantime, our interface can special case Ledger wallets to always send `eth_signTypedData` instead.

https://github.com/LedgerHQ/wallet-connect-live-app/blob/90cf8cd51af2e16ac4470277d85a91184ebcd30e/src/components/WalletConnect/index.tsx#L385

**Comment by mcayuelas-ledger** [comment]
Hey ! 

We have been working mainly on the new version of Wallet Connect. That's why the support of this event had not been added for the moment 

Thank's for feedback :)

**Comment by mcayuelas-ledger** [comment]
Has been solved
