### ISSUE TITLE
Wallet Connect v1 does not pop up signMessage modal for eth_signTypedData 

### ISSUE THREAD

**Issue by ericpan0207** [LedgerHQ/wallet-connect-live-app#61]
There's already a report here: https://github.com/LedgerHQ/ledger-live/issues/2870

Some more details that are specific to my case:
Using Ledger-nano-x and Ledger Live Desktop App.

I wallet connect, using wallet connect v1, to my dapp that uses gnosis safe sdk to sign and execute transactions on chain. When I call gnosis sdk to signTransaction using the eth_signTypedData signing method, there is no popup sign message modal on ledger live desktop for me to be actually sign on my ledger. When I use eth_sign signing method, the popup signing modal does pop up and I'm able to sign on my ledger

There's also another user that did more detailed testing than me that's posted their information on the official discord: https://discord.com/channels/885256081289379850/1081199909904056473/1081199909904056473

**Comment by adrienlacombe-ledger** [comment]
@ericpan0207 this is fixed

**Comment by mcayuelas-ledger** [comment]
As it has been fixed and V1 isn't supported anymore by us. 

Closing the issue
