### ISSUE TITLE
In dApps using Wallet Connect v2, the signatures don't get back to the dApp.

### ISSUE THREAD

**Issue by theotniel** [LedgerHQ/wallet-connect-live-app#65]
We have tested with some dApps referenced in https://github.com/WalletConnect/web-examples and while the account connection works great, it seems that somehow the signed messages never get back to the apps: 

Here are the steps to reproduce:
1. Go to  https://react-app.walletconnect.com/ 
2. Select Ethereum and/or Polygon
3. Click the Connect button
4. Select Ledger -> LLD opens
5. In LLD select ledger accounts to be connected
6. In LLD click **Connect**
7. On the waletconnect app webpage a list of possible methods appears
8. Click `personal_sign`
9. In LLD - Sign message modal appears -> click **Continue**
10. On the ledger device confirm **Sign message**

The expected result is to see the signature and validation status in the waletconnect web app (as in the attached image), but the page just waits forever.
<img width="497" alt="Screenshot 2023-05-11 at 16 33 31" src="https://github.com/LedgerHQ/wallet-connect-live-app/assets/37304045/80b70e8b-2b16-43bd-bd2c-e1b8c50f1a28">

For reference: 
* we have tried the above workflow on the Android Ledger Live app (pixel 7 Pro) and didn't even get to step 9. We have also used both a Nano X and a Nano S
* there are a couple more dApps examples in the repo referenced above and also a third app not listed there. They all behave the same way with LLD and Android LL
* `eth_sign` and `signTypedData` behave the same way as `personal_sign`

More context [on discord](https://discord.com/channels/885256081289379850/1062644137758834688/1106214935043772456).

**Comment by PaulUD** [comment]
`eth_signTransaction` and `eth_sendTransaction` are being processed on chain by the sample React dApp but unfortunately as pointed out the other 3 transaction types are failing.

**Comment by mcayuelas-ledger** [comment]
This problem has been solved recently. Can you confirm?
